steps:
  - id: "hello-ci"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Build do Cloud Build rodando"
        echo "Branch: $BRANCH_NAME"
